# Since DE_analysis employs a pseudo-bulk approach, the subsequent analysis
# here utilizes the output generated by DE_analysis. The four options provided
# within the `rank-index` parameter are all based on the results from DE_analysis.
# If you are using `Seurat::FindMarkers` instead, you may manually modify the
# code to use `avg_log2FC` or `avg_log2FC * -10 * log(p-value)`.
# --Bingtian write on Apr. 6th, 2026

gsea_analysis_from_tsv <- function(file_path,
                              species = "Mus musculus", # "Homo sapiens"
                              gene_col = "segex",
                              ratio_col = "ratio",
                              fc_col = "fc",
                              pval_col = "pvalue_1",
                              method = "fc",  # "log2fc-pvalue", "log2fc", ""，fc-pvalue
                              db = c("GO_BP", "Reactome", "Hallmark")) {
  
  library(clusterProfiler)
  library(msigdbr)
  library(dplyr)
  library(tidyverse)
  set.seed(001203)
  if(!file.exists(file_path)) stop("File does not exist: ", file_path)
  df <- read.delim(file_path, header = TRUE, stringsAsFactors = FALSE)
  
  required_cols <- c(gene_col, ratio_col, fc_col, pval_col)
  missing_cols <- setdiff(required_cols, colnames(df))
  if(length(missing_cols) > 0) stop("Missing columns: ", paste(missing_cols, collapse = ", "))
  
  df[[pval_col]][df[[pval_col]] == 0] <- 1e-300
  
  df <- df %>%
    mutate(rank = switch(method,
                         "fc-pvalue"     = !!sym(fc_col) * -log10(!!sym(pval_col)),
                         "log2fc-pvalue" = log2(!!sym(ratio_col)) * -log10(!!sym(pval_col)),
                         "log2fc"        = log2(!!sym(ratio_col)),
                         "fc"            = !!sym(fc_col),
                         stop("Unknown method: ", method)
    )) %>%
    filter(!is.na(rank))
  
  ranked_list <- df %>%
    select(all_of(gene_col), rank) %>%
    deframe() 
  # add random value to avoid ties
  ranked_list <- ranked_list + rnorm(length(ranked_list), 0, 1e-10)
  ranked_list <- sort(ranked_list, decreasing = TRUE)
  
  gene_sets <- get_gene_sets(species, db)
  
  gsea_results <- lapply(names(gene_sets), function(db_name) {
    
    term2gene <- gene_sets[[db_name]] %>%
      dplyr::select(gs_name, gene_symbol)
    
    tryCatch({
      GSEA(
        geneList = ranked_list,
        TERM2GENE = term2gene,
        minGSSize = 10,
        maxGSSize = 500,
        eps = 0,
        seed = TRUE,
        pvalueCutoff = 1,
        pAdjustMethod = "BH",
        nPermSimple = 10000,
        scoreType = "std",
        verbose = FALSE
      )@result
    }, error = function(e) {
      warning("GSEA failed for db: ", db_name, " - ", e$message)
      return(NULL)
    })
  })
  
  names(gsea_results) <- names(gene_sets)
  
  gsea_results <- gsea_results[!sapply(gsea_results, is.null)] 
  
  return(gsea_results)
  
}

# get gene sets from gsea-msigdb
get_gene_sets <- function(
    species = "Mus musculus", # "Homo sapiens"
    db = c("GO_BP", "Reactome", "Hallmark")
){
  # Comprehensive db_map for MSigDB gene sets
  db_map <- list(
    HS = list(
      Positional = list(category = "C1", subcategory = NULL),
      CGP         = list(category = "C2", subcategory = "CGP"),
      CP          = list(category = "C2", subcategory = "CP"),
      BioCarta    = list(category = "C2", subcategory = "CP:BIOCARTA"),
      KEGG_LEGACY = list(category = "C2", subcategory = "CP:KEGG_LEGACY"),
      KEGG        = list(category = "C2", subcategory = "CP:KEGG_MEDICUS"),
      PID         = list(category = "C2", subcategory = "CP:PID"),
      Reactome    = list(category = "C2", subcategory = "CP:REACTOME"),
      WikiPathways= list(category = "C2", subcategory = "CP:WIKIPATHWAYS"),
      CP_CUSTOM   = list(category = "C2", subcategory = NULL),
      Motif_miR  = list(category = "C3", subcategory = "MIR:MIRDB"),
      Motif_miR_Legacy = list(category = "C3", subcategory = "MIR:MIR_LEGACY"),
      Motif_TF   = list(category = "C3", subcategory = "TFT:GTRD"),
      Motif_TF_Legacy = list(category = "C3", subcategory = "TFT:TFT_LEGACY"),
      Computational = list(category = "C4", subcategory = NULL),
      GO_BP      = list(category = "C5", subcategory = "GO:BP"),
      GO_CC      = list(category = "C5", subcategory = "GO:CC"),
      GO_MF      = list(category = "C5", subcategory = "GO:MF"),
      HPO        = list(category = "C5", subcategory = "HPO"),
      Oncogenic  = list(category = "C6", subcategory = NULL),
      Immune     = list(category = "C7", subcategory = "IMMUNESIGDB"),
      VAX        = list(category = "C7", subcategory = "VAX"),
      Hallmark   = list(category = "H", subcategory = NULL)
    ),
    MM = list(
      Positional = list(category = "M1", subcategory = NULL),
      CGP        = list(category = "M2", subcategory = "CGP"),
      BioCarta   = list(category = "M2", subcategory = "CP:BIOCARTA"),
      Reactome   = list(category = "M2", subcategory = "CP:REACTOME"),
      WikiPathways = list(category = "M2", subcategory = "CP:WIKIPATHWAYS"),
      Motif_TF  = list(category = "M3", subcategory = "GTRD"),
      Motif_miR = list(category = "M3", subcategory = "MIRDB"),
      GO_BP      = list(category = "M5", subcategory = "GO:BP"),
      GO_CC      = list(category = "M5", subcategory = "GO:CC"),
      GO_MF      = list(category = "M5", subcategory = "GO:MF"),
      MP_Tumor   = list(category = "M5", subcategory = "MPT"),
      Immune    = list(category = "M7", subcategory = NULL),
      Hallmark  = list(category = "MH", subcategory = NULL)
    )
  )
  
  supported_species <- c("Homo sapiens", "Mus musculus")
  if (!species %in% supported_species) {
    stop("Error: Unsupported species. Only 'Homo sapiens' and 'Mus musculus' are supported.")
  }
  
  gene_sets <- list()
  db_s <- ifelse(species == "Homo sapiens", "HS", "MM")
  
  for (db_name in db) {
    if (!db_name %in% names(db_map[[db_s]])) {
      warning(paste("Database", db_name, "not found in db_map for species", species, "- skipping."))
      next
    }
    
    category <- db_map[[db_s]][[db_name]]$category
    subcollection <- db_map[[db_s]][[db_name]]$subcategory
    gene_sets[[db_name]] <- msigdbr(db_species = db_s,
                                    species = species,
                                    collection = category,
                                    subcollection = subcollection) %>%
      select(gs_name, gene_symbol)
  }
  return(gene_sets)
}

DEBUG = FALSE
if(DEBUG){
  result <- gsea_analysis_from_tsv(
    "/projectnb/wax-es/00_shinyapp/DEG/test/1_scLoupe_G193M1_Male2_0_vs_G193M2_Male_TCPO_2wk_0_DiffExp_IntronicMonoExonic.tsv",
  )
}