# Since DE_analysis employs a pseudo-bulk approach, the subsequent analysis
# here utilizes the output generated by DE_analysis. The four options provided
# within the `rank-index` parameter are all based on the results from DE_analysis.
# If you are using `Seurat::FindMarkers` instead, you may manually modify the
# code to use `avg_log2FC` or `avg_log2FC * -10 * log(p-value)`.
# --Bingtian write on Apr. 6th, 2026

# In single-cell RNA-seq analysis without biological replicates, pre-ranked GSEA relies
# primarily on gene ranking rather than formal statistical testing. Therefore, interpretation
# should focus on the normalized enrichment score (NES), which reflects both the direction and
# magnitude of pathway enrichment between conditions.
# 
# In contrast, p-values in this context are influenced by cell-level pseudo-replication, which
# violates the assumption of independent samples. As a result, their statistical interpretation
# is limited, and they should only be considered as a supplementary indicator of consistency or
# robustness of the enrichment signal rather than as a primary measure of significance.
# 
# It is not recommended to describe results as “statistically significant enrichment (p < 0.05).”
# Instead, interpretations should avoid over-reliance on p-values.
# 
# A preferred expression should emphasize NES, for example: “This pathway shows positive/negative
# enrichment (NES > 0 / NES < 0), suggesting upregulation/downregulation under condition A.”
# 
# --Bingtian write on Apr. 21th, 2026

gsea_analysis_from_tsv <- function(file_path,
                              species = "Mus musculus", # "Homo sapiens"
                              gene_col = "segex",
                              ratio_col = "ratio",
                              fc_col = "fc",
                              pval_col = "pvalue_1",
                              method = "fc",  # "log2fc-pvalue", "log2fc", ""，fc-pvalue
                              db = c("GO_BP", "Reactome", "Hallmark")) {
  
  library(clusterProfiler)
  library(msigdbr)
  library(dplyr)
  library(tidyverse)
  set.seed(001203)
  if(!file.exists(file_path)) stop("File does not exist: ", file_path)
  df <- read.delim(file_path, header = TRUE, stringsAsFactors = FALSE)
  
  required_cols <- c(gene_col, ratio_col, fc_col, pval_col)
  missing_cols <- setdiff(required_cols, colnames(df))
  if(length(missing_cols) > 0) stop("Missing columns: ", paste(missing_cols, collapse = ", "))
  
  df[[pval_col]][df[[pval_col]] == 0] <- 1e-300
  
  df <- df %>%
    mutate(rank = switch(method,
                         "fc-pvalue"     = !!sym(fc_col) * -log10(!!sym(pval_col)),
                         "log2fc-pvalue" = log2(!!sym(ratio_col)) * -log10(!!sym(pval_col)),
                         "log2fc"        = log2(!!sym(ratio_col)),
                         "fc"            = !!sym(fc_col),
                         stop("Unknown method: ", method)
    )) %>%
    filter(!is.na(rank))
  
  ranked_list <- df %>%
    select(all_of(gene_col), rank) %>%
    deframe() 
  # add random value to avoid ties
  ranked_list <- ranked_list + rnorm(length(ranked_list), 0, 1e-10)
  ranked_list <- sort(ranked_list, decreasing = TRUE)
  
  gene_sets <- get_gene_sets(species, db)
  
  gsea_results <- lapply(names(gene_sets), function(db_name) {
    
    term2gene <- gene_sets[[db_name]] %>%
      dplyr::select(gs_name, gene_symbol)
    
    tryCatch({
      GSEA(
        geneList = ranked_list,
        TERM2GENE = term2gene,
        minGSSize = 10,
        maxGSSize = 500,
        eps = 0,
        seed = TRUE,
        pvalueCutoff = 1,
        pAdjustMethod = "BH",
        nPermSimple = 10000,
        scoreType = "std",
        verbose = FALSE
      )@result
    }, error = function(e) {
      warning("GSEA failed for db: ", db_name, " - ", e$message)
      return(NULL)
    })
  })
  
  names(gsea_results) <- names(gene_sets)
  gsea_results <- gsea_results[!sapply(gsea_results, is.null)]
  
  if (length(gsea_results) > 0) {
    
    combined_df <- dplyr::bind_rows(
      lapply(names(gsea_results), function(db_name) {
        df <- gsea_results[[db_name]]
        if (!is.null(df) && nrow(df) > 0) {
          df$database <- db_name
          return(df)
        }
        return(NULL)
      })
    )
    gsea_results <- c(list(ALL = combined_df), gsea_results)
  }
  
  return(gsea_results)
  
}

# get gene sets from gsea-msigdb
get_gene_sets <- function(
    species = "Mus musculus", # "Homo sapiens"
    db = c("GO_BP", "Reactome", "Hallmark")
){
  # Comprehensive db_map for MSigDB gene sets
  db_map <- list(
    HS = list(
      `H(Hallmark)`              = list(category = "H",  subcategory = NULL),
      
      `C1(Positional)`           = list(category = "C1", subcategory = NULL),
      
      `C2(CGP)`                  = list(category = "C2", subcategory = "CGP"),
      `C2(CP)`                   = list(category = "C2", subcategory = "CP"),
      `C2(CP_BioCarta)`          = list(category = "C2", subcategory = "CP:BIOCARTA"),
      `C2(CP_KEGG_LEGACY)`       = list(category = "C2", subcategory = "CP:KEGG_LEGACY"),
      `C2(CP_KEGG_MEDICUS)`      = list(category = "C2", subcategory = "CP:KEGG_MEDICUS"),
      `C2(CP_PID)`               = list(category = "C2", subcategory = "CP:PID"),
      `C2(CP_Reactome)`          = list(category = "C2", subcategory = "CP:REACTOME"),
      `C2(CP_WikiPathways)`      = list(category = "C2", subcategory = "CP:WIKIPATHWAYS"),
      
      `C3(MIR)`                  = list(category = "C3", subcategory = "MIR"),
      `C3(MIR_MIRDB)`            = list(category = "C3", subcategory = "MIR:MIRDB"),
      `C3(MIR_MIR_LEGACY)`       = list(category = "C3", subcategory = "MIR:MIR_LEGACY"),
      `C3(TFT)`                  = list(category = "C3", subcategory = "TFT"),
      `C3(TFT_GTRD)`             = list(category = "C3", subcategory = "TFT:GTRD"),
      `C3(TFT_TFT_LEGACY)`       = list(category = "C3", subcategory = "TFT:TFT_LEGACY"),
      
      `C4(Computational)`        = list(category = "C4", subcategory = NULL),
      `C4(3CA)`                  = list(category = "C4", subcategory = "3CA"),
      `C4(CGN)`                  = list(category = "C4", subcategory = "CGN"),
      `C4(CM)`                   = list(category = "C4", subcategory = "CM"),
      
      `C5(GO_BP)`                = list(category = "C5", subcategory = "GO:BP"),
      `C5(GO_CC)`                = list(category = "C5", subcategory = "GO:CC"),
      `C5(GO_MF)`                = list(category = "C5", subcategory = "GO:MF"),
      `C5(HPO)`                  = list(category = "C5", subcategory = "HPO"),
      
      `C6(Oncogenic)`            = list(category = "C6", subcategory = NULL),
      
      `C7(ImmuneSigDB)`          = list(category = "C7", subcategory = "IMMUNESIGDB"),
      `C7(VAX)`                  = list(category = "C7", subcategory = "VAX"),
      
      `C8(CellType)`             = list(category = "C8", subcategory = NULL),
      
      `C9(CompPerturb)`          = list(category = "C9", subcategory = NULL)
    ),
    MM = list(
      `M1(Positional)`      = list(category = "M1", subcategory = NULL),
      `M2(CGP)`             = list(category = "M2", subcategory = "CGP"),
      `M2(CP_BioCarta)`     = list(category = "M2", subcategory = "CP:BIOCARTA"),
      `M2(CP_Reactome)`     = list(category = "M2", subcategory = "CP:REACTOME"),
      `M2(CP_WikiPathways)` = list(category = "M2", subcategory = "CP:WIKIPATHWAYS"),
      `M3(MIRDB)`           = list(category = "M3", subcategory = "MIRDB"),
      `M3(GTRD)`            = list(category = "M3", subcategory = "GTRD"),
      `M5(GO_BP)`           = list(category = "M5", subcategory = "GO:BP"),
      `M5(GO_CC)`           = list(category = "M5", subcategory = "GO:CC"),
      `M5(GO_MF)`           = list(category = "M5", subcategory = "GO:MF"),
      `M5(MPT)`             = list(category = "M5", subcategory = "MPT"),
      `M7(Immune)`          = list(category = "M7", subcategory = NULL),
      `M8(Celltype)`        = list(category = "M8", subcategory = NULL),
      `MH(Hallmark)`        = list(category = "MH", subcategory = NULL)
    )
  )
  
  supported_species <- c("Homo sapiens", "Mus musculus")
  if (!species %in% supported_species) {
    stop("Error: Unsupported species. Only 'Homo sapiens' and 'Mus musculus' are supported.")
  }
  
  gene_sets <- list()
  db_s <- ifelse(species == "Homo sapiens", "HS", "MM")
  
  for (db_name in db) {
    if (!db_name %in% names(db_map[[db_s]])) {
      warning(paste("Database", db_name, "not found in db_map for species", species, "- skipping."))
      next
    }
    
    category <- db_map[[db_s]][[db_name]]$category
    subcollection <- db_map[[db_s]][[db_name]]$subcategory
    gene_sets[[db_name]] <- msigdbr(db_species = db_s,
                                    species = species,
                                    collection = category,
                                    subcollection = subcollection) %>%
      select(gs_name, gene_symbol)
  }
  return(gene_sets)
}

DEBUG = FALSE
if(DEBUG){
  result <- gsea_analysis_from_tsv(
    "/projectnb/wax-es/00_shinyapp/DEG/test/1_scLoupe_G193M1_Male2_0_vs_G193M2_Male_TCPO_2wk_0_DiffExp_IntronicMonoExonic.tsv",
  )
}